{% set name = "splunk_handler" %}
{% set version = "2.2.2" %}
{% set sha256 = "1a2374f1ce2f488fd8e4340460a74804c25ac44a5932fbc287bfc8e7355a1dc5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip

  run:
    - python >=2.7
    - requests

test:
  imports:
    - splunk_handler

about:
  home: https://github.com/zach-taylor/splunk_handler
  doc_url: https://github.com/zach-taylor/splunk_handler
  dev_url: https://github.com/zach-taylor/splunk_handler
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python logging handler that sends your logs to Splunk'

  description: |
      Splunk Handler is a Python Logger for sending logged events to an installation
      of Splunk Enterprise. This logger requires the destination Splunk Enterprise 
      server to have enabled and configured the Splunk HTTP Event Collector.

extra:
  recipe-maintainers:
    - sodre
